// <auto-generated />
using System;
using GestorMotosRetenidas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorMotosRetenidas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250527030742_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorMotosRetenidas.Models.Infractor", b =>
                {
                    b.Property<int>("DniInfractor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DniInfractor"));

                    b.Property<string>("ApellidoInfractor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreInfractor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DniInfractor");

                    b.ToTable("Infractores");
                });

            modelBuilder.Entity("GestorMotosRetenidas.Models.Moto", b =>
                {
                    b.Property<int>("NroRetencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroRetencion"));

                    b.Property<int>("DniInfractor")
                        .HasColumnType("int");

                    b.Property<int>("DniTitular")
                        .HasColumnType("int");

                    b.Property<int>("EstadoMoto")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRetencion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MotivoRetencion")
                        .HasColumnType("int");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NroRetencion");

                    b.HasIndex("DniInfractor");

                    b.HasIndex("DniTitular");

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("GestorMotosRetenidas.Models.Titular", b =>
                {
                    b.Property<int>("DniTitular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DniTitular"));

                    b.Property<string>("ApellidoTitular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreTitular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DniTitular");

                    b.ToTable("Titulares");
                });

            modelBuilder.Entity("GestorMotosRetenidas.Models.Moto", b =>
                {
                    b.HasOne("GestorMotosRetenidas.Models.Infractor", "infractor")
                        .WithMany()
                        .HasForeignKey("DniInfractor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorMotosRetenidas.Models.Titular", "titular")
                        .WithMany()
                        .HasForeignKey("DniTitular")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("infractor");

                    b.Navigation("titular");
                });
#pragma warning restore 612, 618
        }
    }
}
